### PR TITLE
Issue 31 Waits till previously scheduled task is finished, then a new one is scheduled

### PR DESCRIPTION
**Pull request by smiklosovic**

### CODE REVIEW

**Comment by smiklosovic** [comment]
@MatousJobanek 

I tried to add a test for #31 on top of your commit but Travis build failed with this

https://travis-ci.org/arquillian/arquillian-spacelift/jobs/235571830

**Comment by smiklosovic** [comment]
I ve just increased the until timeout to be 15 seconds instead of 10. It would do it with 11 as well. The thing is that sometimes it will just not be executed in 10 seconds sharp so it throws timeout exception ...

**Comment by bartoszmajsak** [comment]
I'm not really sure what happened here. You closed original PR, then opened this one without giving original author a chance to respond and then merged it immediately? Why?

**Comment by smiklosovic** [comment]
Because I would have to create PR against his branch and wait until he merges that and pushes it again so I wrote that test myself from his branch, pushed into this repository and merged it so his PR became not relevant anymore.

**Comment by bartoszmajsak** [comment]
For me it's more about communication, to be honest.

Also, so for PR to @MatousJobanek branch - you could just ask to get push rights for his PR if not enabled by default. It's been a while

**Comment by smiklosovic** [comment]
I have been a coleague of Matus for two years maybe and I am grateful for his work everytime and he knows it. It does not matter for me who does what I would be surprised if he took that personally, I would be totally fine if he did the same thing.

**Comment by bartoszmajsak** [comment]
I don't think anyone took it personally. In fact I didn't even speak with @MatousJobanek about it. But it just looks like that. Normally I would ask if that's fine to take over. Just a matter of transparency and collaboration.

**Comment by MatousJobanek** [comment]
Hi guys.
No, I don't take this personally at all :-D. It was just kind of surprise - at the first moment. I didn't know what was going on. I also planned to write a test for it, but when you did it then it is completely fine. Yeah, maybe some warning or comment what are going to do would be helpful also for the others - not to do the same thing twice...
BTW, it's nice to see you back in Arquillian community after short break 👍

**Pull request merged**
